<?php
include 'Chessmen.php';

class King extends Chessmen
{
    public function __construct($x, $y){
        $this->x = $x;
        $this->y = $y;
    }

    public function getPosition()
    {
        echo 'Король ' . parent::getPosition(); // TODO: Change the autogenerated stub
    }

    public function move($x, $y){



         if($x < 1 || $x > 8 || $y < 1 || $y > 8){
             throw new Exception('Вы переместились за край шахматной доски');
         }

         if($this->x > $x && $this->y == $y){

                if($this->x - $x !== 1){
                    throw new Exception('Король не может так ходить, учите правила шахмат');
                }

             $this->x = $x;
             $this->getPosition();
         }

         if($this->x < $x && $this->y == $y){

             if($x - $this->x !== 1){
                 throw new Exception('Король не может так ходить, учите правила шахмат');
             }

             $this->x = $x;
             $this->getPosition();
         }

         if($this->x == $x && $this->y > $y){

             if($this->y - $y !== 1){
                 throw new Exception('Король не может так ходить, учите правила шахмат');
             }

             $this->y = $y;
             $this->getPosition();
         }

         if($this->x == $x && $this->y < $y){

             if($y - $this->y !== 1){
                 throw new Exception('Король не может так ходить, учите правила шахмат');
             }

             $this->y = $y;
             $this->getPosition();
         }

         if($this->x < $x && $this->y > $y){

             if($this->y - $y !== 1 || $x - $this->x !== 1){
                 throw new Exception('Король не может так ходить, учите правила шахмат');
             }

             $this->x = $x;
             $this->y = $y;
             $this->getPosition();
         }

         if($this->x > $x && $this->y < $y){

             if($this->x - $x !== 1 || $y - $this->y !== 1){
                 throw new Exception('Король не может так ходить, учите правила шахмат');
             }

             $this->x = $x;
             $this->y = $y;
             $this->getPosition();
         }

         if($this->x > $x && $this->y > $y){

             if($this->x - $x !== 1 || $this->y - $y !== 1){
                 throw new Exception('Король не может так ходить, учите правила шахмат');
             }

             $this->x = $x;
             $this->y = $y;
             $this->getPosition();
         }

         if($this->x < $x || $this->y < $y){

             if($x - $this->x !== 1 || $y - $this->y !== 1){
                 throw new Exception('Король не может так ходить, учите правила шахмат');
             }

             $this->x = $x;
             $this->y = $y;
             $this->getPosition();
         }
    }
}